// <auto-generated />
namespace EF_Task.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201309251333285_AddClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
